# Generated by Django 2.2.5 on 2019-09-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('gender', models.IntegerField(choices=[(1, 'man'), (2, 'woman'), (0, 'unknown')], verbose_name='gender')),
                ('profession', models.CharField(max_length=128, verbose_name='profession')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tel', models.CharField(max_length=128, verbose_name='telephone')),
                ('status', models.IntegerField(choices=[(0, 'apply'), (1, 'pass'), (2, 'reject')], default=0, verbose_name='Check-state')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'verbose_name': 'student information',
                'verbose_name_plural': 'student information',
            },
        ),
    ]
